### ISSUE TITLE
Menu

### ISSUE THREAD

**Issue by griz894** [arnecls/raidplaner#141]
Hi,
I need to add a link to my website homepage.
where i add my href ? 

thanks

**Comment by arnecls** [comment]
In the settings "banner link".

**Comment by griz894** [comment]
thank you very much.

Other question,
i have create a new template for the game aion, the xml files is proper, all class are created correctly.

Or the icons of the class (in the folder aion\iconesmall etc..) was not used.

(sorry for my english)
thanks you
