### ISSUE TITLE
Problems when using Logged_in_key and logged_in_salt

### ISSUE THREAD

**Issue by LeonGeb** [arnecls/raidplaner#144]
I installed 1.1.4 and was able to setup and connect to wordpress (4.2.2.). However, I can't use the auto-login. I entered the logged_in_key and logged_in_salt into the field when connecting/editing the binding to wordpress and checked "auto login" - it still doesn't work. I tried different ways to enter both keys (the explanation above the field is not really clear).

On Google Chrome it shows only white screen, on opera it shows error "LOCA Missing"

**Comment by arnecls** [comment]
Did you try to use the auto-detection? Entering the values manually is somewhat tricky.
Also please read this page regarding automatic login: https://github.com/arnecls/raidplaner/wiki/Automatic-login-troubleshooting

If the problem still persists I'll have to have a look at your setup to find the error.

**Comment by LeonGeb** [comment]
Hi Arne,
Thanks for your quick reply. No I didn't use auto-detection because I had all the information. Its working now thanks alot!

**Comment by arnecls** [comment]
nice to hear :)
