### ISSUE TITLE
FF14 - New Classes

### ISSUE THREAD

**Issue by glookie1** [arnecls/raidplaner#145]
There are 3 new classes in FF14 Heavensward.

Dark Knight (Tank)
Machinist (Range DPS)
Astologian (Healer)

Can they be added and if yes where? I looked through your code but I just can't find my way around webstuff. :/

**Comment by arnecls** [comment]
This can be changed in the [game config for ff14].(https://github.com/arnecls/raidplaner/blob/master/themes/games/ff14.xml).
If you can send me the icons for that classes I will integrate those.

**Comment by glookie1** [comment]
https://imgur.com/a/kO6QS Top to bottom: Machinist, Astrologian, Dark Knight.

Thank you :)

**Comment by arnecls** [comment]
Pushed directly to master.
You can download the changes in "themes/icons/ff14/classessmall", "themes/icons/ff14/classesbig" and "themes/games/ff14.xml".

Please check if this is ok for you :)

**Comment by glookie1** [comment]
Perfect. I still don't know where you got those icons from. xD
