### ISSUE TITLE
Uncaught TypeError: Cannot read property 'name' of undefined - raidplaner.js Zeile 710 

### ISSUE THREAD

**Issue by Eikju** [arnecls/raidplaner#155]
Hey there :).

I got the problem that the tooltip won't show up again, if you click once on "not attending" Drop-Down-Arrows and then click again on the "not attending"-button.

So you also can't sign out again on that event - it's buged 4 ever.

The error-message is:
`Uncaught TypeError: Cannot read property 'name' of undefined - raidplaner.js Zeile 710 `

Here is a little demonstration:
https://youtu.be/6hXIL7fRlAs

**Comment by arnecls** [comment]
You shouldn't be able to select that option (with an action) in the first place ... I'll see that I disable this one.

**Comment by arnecls** [comment]
To fix the "stuck" users, move them to absent from the raid view (and back again if you wish to).
This should overwrite the value causing the problem.

This here should disable the possibility to click that option in the first place: [patch.zip](https://github.com/arnecls/raidplaner/files/139892/patch.zip).
I wasn't able to test this yet though as I have to setup a dev env first (my hdd got toasted a while ago and I haven't set up a dev environment, yet). So either try this one (make a backup!) or wait a few days until I got the environment up running agian.

**Comment by Eikju** [comment]
HEy @arnecls :)

Then I will wait. Take it easy and thank you for the help :)

**Comment by Eikju** [comment]
I tested your patch.zip out but it does not work. You can still clock on that kind of option. So it is still buged :)

**Comment by arnecls** [comment]
You need to enable script debugging for the patch to work.
Index.php line 4, replace false with true

**Comment by Eikju** [comment]
Okay. Now it works. Thank you :)

**Comment by arnecls** [comment]
:+1: I could now test it locally, too, so everything looks fine

**Comment by arnecls** [comment]
Fix pushed to master
