### ISSUE TITLE
Demonhunter Issue

### ISSUE THREAD

**Issue by k1von3** [arnecls/raidplaner#157]
After I have loaded the new files you've updated 6 days ago I got this message:

LOCA_MISSING_RequestError

PHP Error 2 in file tools_site.php(202):\nSimpleXMLElement::__construct() [simplexmlelement.--construct]: Entity: line 137: parser error : Input is not proper UTF-8, indicate encoding !
Bytes: 0xE4 0x67 0x65 0x72\n\nCallstack:\ndebug.php(46) : root\n

And it doesn't work either.

Is there any way to add the demonhunter stuff? Or will it be able in another release? I am not good in this - just wanted to ask.

Great work already, thanks alot! - Do you have a twitter account?
--------------------------

Auf Deutsch:
Ich habe keine Ahnung von dem ganzen Zeug - wollte den Dämonenjäger integrieren, habe die Zeilen hinzugefügt, die Du kürzlich verändert hast.

Müssen noch andere Dateien verändert werden das es funktioniert?

Grüße

**Comment by arnecls** [comment]
To be honest I tested the changes only rather quickly so this is probably a bug on my side (encoding error).

Could you give me some information about your setup?
Which game config do you use for wow? pro or normal?
Which version of PHP do you use? 5.x or 7?

**Comment by arnecls** [comment]
Ah - just read your german comment.
You need to save your document as UTF8 otherwise it cannot be parsed correctly.
What Editor do you use for editing?

**Comment by k1von3** [comment]
Ich nutze WinSCP - dabei wird das Format eigentlich nicht verändert.

Nachdem ich es wieder resettet hatte ging es - genauso wie vorher.
Nur die Klasse Dämonenjäger habe ich eben nicht. Wenn es nicht zu viele Umstände macht, gibt es die Möglichkeit ein Step by Step-für Dumme aufzuschreiben?

Also ich weiß schon mal wie ich die Datei finde usw - aber anscheinend mache ich ja was falsch^^

Grüße

**Comment by arnecls** [comment]
Wenn du die Datei direkt hochlädst sollte das encoding nicht verändert werden. Außer WinSCP macht da Sachen die es nicht soll.
Wenn du die Datei vorher editierst, dann kann es sein, dass dein Editor das Encoding der Datei beim Speichern verändert. Das Windows Notepad macht das z.B. gerne mal.

Wenn du unter Windows unterwegs bist, dann lade dir am besten mal [Notepad++](https://notepad-plus-plus.org/download/v6.9.2.html) runter. Damit kannst du das Encoding überprüfen und ändern.
Unten im Fenster (2. Feld von rechts) steht das Encoding. Wenn da "UTF-8" steht ist alles in Ordnung. Steht da "ANSI" oder irgendwas anderes, dann kannst du über das Menü "Encoding" die Datei nach UTF-8 (kein BOM) konvertieren.

**Comment by k1von3** [comment]
Ich danke dir - es funktioniert einwandfrei!!! Nochmal SORRY für die Unannehmlichkeiten :(

**Comment by arnecls** [comment]
Wenn ich schon nicht viel am raidplaner mache, dann kann ich wenigstens bei Bugs helfen ^^.
---
For english readers:
If you get the error "Input is not proper UTF-8, indicate encoding" you XML file is not properly encoded. To fix this you need to install an editor that is capable of displaying and changing the encoding of a file like [textwrangler](https://itunes.apple.com/de/app/textwrangler/id404010395?mt=12) or [notepad++](https://notepad-plus-plus.org).
Make sure that all XML files that you changed are either edited with those editors (as they keep the encoding) or convert them to UTF8 (no BOM).
